name: bot_spamer
services:
  postgre:
    image: postgres:latest
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/root/redis

  bot:
    build:
      context: .
    env_file:
      - .env
    depends_on:
      postgre:
        condition: service_started
      redis:
        condition: service_started
    command: sh /service/docker/startup.sh