"""added cascade delete to table user

Revision ID: 151d8e54cb8c
Revises: 3b7db8bee469
Create Date: 2024-09-17 16:36:25.979975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '151d8e54cb8c'
down_revision: Union[str, None] = '3b7db8bee469'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_account_id_fkey', 'user', type_='foreignkey')
    op.create_foreign_key(None, 'user', 'account', ['account_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.create_foreign_key('user_account_id_fkey', 'user', 'account', ['account_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###
