"""new column spam_msg in table account

Revision ID: 27cc32154577
Revises: 6494d4129d51
Create Date: 2024-09-15 23:11:15.425751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27cc32154577'
down_revision: Union[str, None] = '6494d4129d51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('spam_msg', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account', 'spam_msg')
    # ### end Alembic commands ###
