"""new column is_sent in table user

Revision ID: 3b7db8bee469
Revises: 48b4051f002f
Create Date: 2024-09-17 15:02:45.128243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b7db8bee469'
down_revision: Union[str, None] = '48b4051f002f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_sent', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_sent')
    # ### end Alembic commands ###
