"""new column is_active in table account

Revision ID: 6e9c393921d4
Revises: 27cc32154577
Create Date: 2024-09-15 23:25:11.203458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e9c393921d4'
down_revision: Union[str, None] = '27cc32154577'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account', 'is_active')
    # ### end Alembic commands ###
